on: [push]

env:
  UNITTESTING_TAG: master

jobs:
  linux:
    runs-on: ubuntu-latest
    container: sublimetext/unittesting
    steps:
      - uses: actions/checkout@v1
      - run: sh -e /etc/init.d/xvfb start
      - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.sh
      - run: |
          PATH="$HOME/.local/bin:$PATH"
          sh github.sh bootstrap
          sh github.sh install_package_control
          sh github.sh run_tests

  # macos:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.sh
  #     - run: |
  #         export PATH="$HOME/.local/bin:$PATH"
  #         sh github.sh bootstrap
  #         sh github.sh install_package_control
  #         sh github.sh run_tests

  # windows:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - run: (new-object net.webclient).DownloadFile("https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.ps1","github.ps1")
  #     - run: |
  #         ./github.ps1 "bootstrap" -verbose
  #         ./github.ps1 "install_package_control" -verbose
  #         ./github.ps1 "run_tests" -verbose

  clojure:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.5'

      - uses: DeLaGuardo/setup-clojure@3.3
        with:
          cli: '1.10.3.810'

      - name: Cache Maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Cache Git dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gitlibs
          key: ${{ runner.os }}-gitlibs-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-gitlibs

      - name: Run Clojure tests
        run: clojure -X:dev:shadow-cljs user/-main
        working-directory: ./clojure
